.TH PTHREAD_SELF 3 LinuxThreads

.SH NAME
pthread_self \- return identifier of current thread

.SH SYNOPSIS
#include <pthread.h>

pthread_t pthread_self(void);

.SH DESCRIPTION
\fBpthread_self\fP return the thread identifier for the calling thread.

.SH AUTHOR
Xavier Leroy <Xavier.Leroy@inria.fr>

.SH "SEE ALSO"
\fBpthread_equal\fP(3),
\fBpthread_join\fP(3),
\fBpthread_detach\fP(3),
\fBpthread_setschedparam\fP(3),
\fBpthread_getschedparam\fP(3).

